meta_product_name: "Cooloc"
meta_title: "Cooloc - Simple Pratique Amusant"
meta_description: "Avec cooloc, fini les disputes
interminable pour savoir qui va faire le ménage, nettoyer les vitres, laver le sol... L'application
s'occupe de tout, laissez-vous guider et amusez-vous."
meta_image: "logo-facebook.png" # doit exister dans `app / assets / images /`
